### ISSUE TITLE
ManagedCred にて、 次の様なエラーが出ます。

### ISSUE THREAD

**Issue by juner** [tumbling-dice/snippets#1]
実行すると次の様なエラーが出ます。

マネージ デバッグ アシスタント 'FatalExecutionEngineError' : 'ランタイムの重大なエラーが発生しました。エラーのアドレスは 0x736ac430、スレッド 0x1e48 です。エラー コードは 0xc0000005 です。これは CLR のバグであるか、またはユーザー コードのアンセーフまたは確認不可能な部分にバグがある可能性があります。このバグの一般的な原因には、スタックが壊れる可能性のある COM-interop または PInvoke のユーザー マーシャリング エラーが含まれています。

**Comment by juner** [comment]
https://github.com/tumbling-dice/snippets/blob/d90047d84d0ee59ee4afd5fd986368c34f97f9de/C%20Sharp/ManagedCred/ManagedCred/Credential.cs#L196
具体的にはここの処理でエラーとなります。

**Comment by tumbling-dice** [comment]
パッチを当てたので動作確認してもらえますか。
